# Use the official lightweight Node.js 12 image.
# https://hub.docker.com/_/node
FROM node:12-slim

# Create and change to the app directory.
WORKDIR /usr/src/app

RUN mkdir -p /usr/src/app/uploads

# Copy local code to the container image.
COPY . ./

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

RUN npm install pm2 -g && npm install --only=production && \
npm run postinstall && cp .env.prod .env

EXPOSE 3000

# Run the web service on container startup.
CMD [ "pm2-runtime", "./dist/index.js" ]