FROM node:lts-alpine
WORKDIR /usr/src/app
RUN npm install -g serve
COPY . .
RUN npm install
RUN npm install -g react-scripts
RUN react-scripts build
EXPOSE 3000
CMD [ "serve", "-l", "3000", "-s", "build/" ]
